from os import environ as env

FLUXO = env['FLUXO']

USUARIO_DIA = env['USUARIO_DIA']
USUARIO_RENNER = env['USUARIO_RENNER']

SENHA_DIA = env['SENHA_DIA']
SENHA_RENNER = env['SENHA_RENNER']

ID_ENTRADA_EMPRESA = env['ID_ESCOLHA_EMPRESA']
ID_ENTRADA_NUMERO_CHAMADO = env['ID_ENTRADA_NUMERO_CHAMADO']

