from os import environ as env


AUTH = env['AUTH_UMBLER']
ORGANIZATION_ID = env['ORGANIZATION_ID']

USUARIO_DIA = env['USUARIO_DIA']
USUARIO_RENNER = env['USUARIO_RENNER']

SENHA_DIA = env['SENHA_DIA']
SENHA_RENNER = env['SENHA_RENNER']

ID_ENTRADA_EMPRESA = env['ID_ENTRADA_EMPRESA']
ID_ENTRADA_NUMERO_CHAMADO = env['ID_ENTRADA_NUMERO_CHAMADO']

